// Mocks generated by Mockito 5.4.0 from annotations
// in keylol_api/test/keylol_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dio/dio.dart' as _i2;
import 'package:keylol_api/keylol.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Keylol].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeylol extends _i1.Mock implements _i3.Keylol {
  MockKeylol() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio dio() => (super.noSuchMethod(
        Invocation.method(
          #dio,
          [],
        ),
        returnValue: _FakeDio_0(
          this,
          Invocation.method(
            #dio,
            [],
          ),
        ),
      ) as _i2.Dio);
  @override
  void addInterceptor(_i2.Interceptor? interceptor) => super.noSuchMethod(
        Invocation.method(
          #addInterceptor,
          [interceptor],
        ),
        returnValueForMissingStub: null,
      );
}
