// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'thread.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Thread _$ThreadFromJson(Map<String, dynamic> json) => Thread(
      json['tid'] as String,
      json['fid'] as String,
      json['posttableid'] as String,
      json['typeid'] as String,
      json['sortid'] as String,
      stringToInt(json['readperm'] as String),
      stringToInt(json['price'] as String),
      json['author'] as String,
      json['authorid'] as String,
      json['subject'] as String,
      json['dateline'] as String,
      json['lastpost'] as String,
      json['lastposter'] as String,
      stringToInt(json['views'] as String),
      stringToInt(json['replies'] as String),
      stringToInt(json['displayorder'] as String),
      json['highlight'] as String,
      stringToBool(json['digest'] as String),
      json['rate'] as String,
      json['special'] as String,
      json['attachment'] as String,
      json['moderated'] as String,
      json['closed'] as String,
      json['stickreply'] as String,
      stringToInt(json['recommends'] as String),
      json['recommend_add'] as String,
      json['recommend_sub'] as String,
      stringToInt(json['heats'] as String),
      json['status'] as String,
      stringToBool(json['isgroup'] as String),
      stringToInt(json['favtimes'] as String),
      stringToInt(json['sharetimes'] as String),
      json['stamp'] as String,
      json['icon'] as String,
      json['pushedaid'] as String,
      json['cover'] as String,
      json['replycredit'] as String,
      stringToInt(json['maxposition'] as String),
      json['bgcolor'] as String,
      stringToInt(json['comments'] as String),
      stringToBool(json['hidden'] as String),
      json['linksubmit'] as String,
      json['threadtable'] as String,
      json['threadtableid'] as String,
      stringToInt(json['addviews'] as String),
      stringToInt(json['allreplies'] as String),
      stringToBool(json['is_archived'] as String),
      json['subjectenc'] as String,
      json['short_subject'] as String,
      json['replycredit_rule'],
    );

Map<String, dynamic> _$ThreadToJson(Thread instance) => <String, dynamic>{
      'tid': instance.tid,
      'fid': instance.fid,
      'posttableid': instance.postTableId,
      'typeid': instance.typeId,
      'sortid': instance.sortId,
      'readperm': stringFromInt(instance.readPerm),
      'price': stringFromInt(instance.price),
      'author': instance.author,
      'authorid': instance.authorId,
      'subject': instance.subject,
      'dateline': instance.dateline,
      'lastpost': instance.lastPost,
      'lastposter': instance.lastPoster,
      'views': stringFromInt(instance.views),
      'replies': stringFromInt(instance.replies),
      'displayorder': stringFromInt(instance.displayOrder),
      'highlight': instance.highlight,
      'digest': stringFromBool(instance.digest),
      'rate': instance.rate,
      'special': instance.special,
      'attachment': instance.attachment,
      'moderated': instance.moderated,
      'closed': instance.closed,
      'stickreply': instance.stickReply,
      'recommends': stringFromInt(instance.recommends),
      'recommend_add': instance.recommendAdd,
      'recommend_sub': instance.recommendSub,
      'heats': stringFromInt(instance.heats),
      'status': instance.status,
      'isgroup': stringFromBool(instance.isGroup),
      'favtimes': stringFromInt(instance.favTimes),
      'sharetimes': stringFromInt(instance.shareTimes),
      'stamp': instance.stamp,
      'icon': instance.icon,
      'pushedaid': instance.pushedAId,
      'cover': instance.cover,
      'replycredit': instance.replyCredit,
      'maxposition': stringFromInt(instance.maxPosition),
      'bgcolor': instance.bgColor,
      'comments': stringFromInt(instance.comments),
      'hidden': stringFromBool(instance.hidden),
      'linksubmit': instance.linkSubmit,
      'threadtable': instance.threadTable,
      'threadtableid': instance.threadTableId,
      'addviews': stringFromInt(instance.addViews),
      'allreplies': stringFromInt(instance.allReplies),
      'is_archived': stringFromBool(instance.isArchived),
      'subjectenc': instance.subjectEnc,
      'short_subject': instance.shortSubject,
      'replycredit_rule': instance.replyCreditRule,
    };
