// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'thread.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Thread _$ThreadFromJson(Map<String, dynamic> json) => Thread(
      json['tid'] as String,
      json['fid'] as String,
      json['posttableid'] as String,
      json['typeid'] as String,
      json['sortid'] as String,
      json['readperm'] as int,
      json['price'] as int,
      json['author'] as String,
      json['authorid'] as String,
      json['subject'] as String,
      json['dateline'] as String,
      json['lastpost'] as String,
      json['lastposter'] as String,
      json['views'] as int,
      json['replies'] as int,
      json['displayorder'] as int,
      json['highlight'] as String,
      json['digest'] as bool,
      json['rate'] as int,
      json['special'] as int,
      json['attachment'] as int,
      json['moderated'] as int,
      json['closed'] as int,
      json['stickreply'] as int,
      json['recommends'] as int,
      json['recommend_add'] as int,
      json['recommend_sub'] as int,
      json['heats'] as int,
      json['status'] as String,
      json['isgroup'] as int,
      json['favtimes'] as int,
      json['sharetimes'] as int,
      json['stamp'] as String,
      json['icon'] as String,
      json['pushedaid'] as String,
      json['cover'] as String,
      json['replycredit'] as int,
      json['relatedbytag'] as String,
      json['maxposition'] as int,
      json['bgcolor'] as String,
      json['comments'] as int,
      json['hidden'] as int,
      json['linksubmit'] as int,
      json['threadtable'] as String,
      json['threadtableid'] as String,
      json['addviews'] as int,
      json['allreplies'] as int,
      json['is_archived'] as bool,
      json['archived'] as int,
      json['subjectenc'] as String,
      json['short_subject'] as String,
      json['replycredit_rule'],
      json['recommendlevel'] as String,
      json['heatlevel'] as String,
      json['relay'] as String,
    );

Map<String, dynamic> _$ThreadToJson(Thread instance) => <String, dynamic>{
      'tid': instance.tid,
      'fid': instance.fid,
      'posttableid': instance.postTableId,
      'typeid': instance.typeId,
      'sortid': instance.sortId,
      'readperm': instance.readPerm,
      'price': instance.price,
      'author': instance.author,
      'authorid': instance.authorId,
      'subject': instance.subject,
      'dateline': instance.dateline,
      'lastpost': instance.lastPost,
      'lastposter': instance.lastPoster,
      'views': instance.views,
      'replies': instance.replies,
      'displayorder': instance.displayOrder,
      'highlight': instance.highlight,
      'digest': instance.digest,
      'rate': instance.rate,
      'special': instance.special,
      'attachment': instance.attachment,
      'moderated': instance.moderated,
      'closed': instance.closed,
      'stickreply': instance.stickReply,
      'recommends': instance.recommends,
      'recommend_add': instance.recommendAdd,
      'recommend_sub': instance.recommendSub,
      'heats': instance.heats,
      'status': instance.status,
      'isgroup': instance.isGroup,
      'favtimes': instance.favTimes,
      'sharetimes': instance.shareTimes,
      'stamp': instance.stamp,
      'icon': instance.icon,
      'pushedaid': instance.pushedAId,
      'cover': instance.cover,
      'replycredit': instance.replyCredit,
      'relatedbytag': instance.relatedByTag,
      'maxposition': instance.maxPosition,
      'bgcolor': instance.bgColor,
      'comments': instance.comments,
      'hidden': instance.hidden,
      'linksubmit': instance.linkSubmit,
      'threadtable': instance.threadTable,
      'threadtableid': instance.threadTableId,
      'addviews': instance.addViews,
      'allreplies': instance.allReplies,
      'is_archived': instance.isArchived,
      'archived': instance.archived,
      'subjectenc': instance.subjectEnc,
      'short_subject': instance.shortSubject,
      'replycredit_rule': instance.replyCreditRule,
      'recommendlevel': instance.recommendLevel,
      'heatlevel': instance.heatLevel,
      'relay': instance.relay,
    };
